### PR TITLE
fix: Correct address from which events are emitted

### LINKED ISSUE #252: Can't read events from a proxy contract
Reading events works as expected when reading from a normal contract, but if we use a proxy contract no events are returned when querying the proxy. On the other hand, events are returned when querying the implementation contract. This is the opposite of how an EVM node behaves.

I've made [a simple project](https://github.com/krebernisak/optimism-tutorial) to demonstrate this behavior.

I've set up a simple ERC20 implementation + OZ Proxy contract:

1. Deploy ERC20 implementation contract
2. Deploy OZ Proxy using 👆 address as implementation
3. Initialize ERC20 contract using `proxy.init`
4. Make 2x Transfer using `proxy.transfer`
5. Try to read events...

Events are read using Ethers v5 and this snippet of code:

```javascript
  const _queryFilterTransfer = async (queryContract, filterContract) => {
    // Get the filter
    const filter = filterContract.filters.Transfer(null, null, null);
    // Query the filter
    return await queryContract.queryFilter(filter, 0, "latest");
  };

  // Test 1
  const logs1 = await _queryFilterTransfer(impl, impl);
  console.log(`Query{impl}  + Filter{impl}:  Expecting 0, got ${logs1.length}`);

  // Test 2
  const logs2 = await _queryFilterTransfer(impl, contract);
  console.log(`Query{impl}  + Filter{proxy}: Expecting 0, got ${logs2.length}`);

  // Test 3
  const logs3 = await _queryFilterTransfer(contract, impl);
  console.log(`Query{proxy} + Filter{impl}:  Expecting 2, got ${logs3.length}`);

  // Test 4
  const logs4 = await _queryFilterTransfer(contract, contract);
  console.log(`Query{proxy} + Filter{proxy}: Expecting 2, got ${logs4.length}`);
 ```

Testing ERC20 proxy on EVM:

```
Query{impl}  + Filter{impl}:  Expecting 0, got 0
Query{impl}  + Filter{proxy}: Expecting 0, got 0
Query{proxy} + Filter{impl}:  Expecting 2, got 2
Query{proxy} + Filter{proxy}: Expecting 2, got 2
```

Testing ERC20 proxy on OVM:

```
Query{impl}  + Filter{impl}:  Expecting 0, got 2
Query{impl}  + Filter{proxy}: Expecting 0, got 2
Query{proxy} + Filter{impl}:  Expecting 2, got 0
Query{proxy} + Filter{proxy}: Expecting 2, got 0
```

### PR DESCRIPTION
**Pull request by smartcontracts**
## Description
Should fix #252. Issue was that the address being attached to the event was the EVM's current address and not the OVM's current address. Event address now comes directly from the execution manager.

### Fixes
- Fixes #252 

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](./CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

File: core/vm/evm.go [hunk 1]
```diff
@@ -707,3 +700,12 @@ func (evm *EVM) Create2(caller ContractRef, code []byte, gas uint64, endowment *
 
 // ChainConfig returns the environment's chain configuration
 func (evm *EVM) ChainConfig() *params.ChainConfig { return evm.chainConfig }
+
+// OvmADDRESS will be set by the execution manager to the target address whenever it's
+// about to create a new contract. This value is currently stored at the [15] storage slot.
+// Can pull this specific storage slot to get the address that the execution manager is
+// trying to create to, and create to it.
+func (evm *EVM) OvmADDRESS() common.Address {
```
Comment (smartcontracts) [inline core/vm/evm.go:708]: Moved this into its own function to avoid duplicating code all over the place.

File: core/vm/instructions.go [hunk 2]
```diff
@@ -895,7 +895,7 @@ func makeLog(size int) executionFunc {
 
 		d := memory.GetCopy(mStart.Int64(), mSize.Int64())
 		interpreter.evm.StateDB.AddLog(&types.Log{
-			Address: contract.Address(),
+			Address: interpreter.evm.OvmADDRESS(),
```
Comment (smartcontracts) [inline core/vm/instructions.go]: Need OVM's address, not EVM's address.

**Comment by tynes** [comment]
We need test coverage around this

**Comment by tynes** [comment]
@smartcontracts How is the testing coming along with this?

**Comment by K-Ho** [comment]
Reminder that this is blocking Chainlink integration, which is thus blocking Synthetix exchange

**Comment by tynes** [comment]
Integration tests passing: https://github.com/ethereum-optimism/optimism-integration/pull/104
